spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:0.5b
          temperature: 0.7
app:
  card-account-api:
    base-url: "http://localhost:3000/"
    get-card-by-uuid: "/cards/"
    block-card-by-uuid: "/cards/block/"
  invoice-api:
    base-url: "http://localhost:3000/"
    get-invoice-by-uuid: "/invoices/"